### ISSUE TITLE
angularjs error

### ISSUE THREAD

**Issue by cosenal** [owncloud-archive/news-mobile#18] opened 2014-01-25 12:04 UTC
Again, app from the marketplace

![2014-01-25-12-56-49](https://f.cloud.github.com/assets/1048336/2001583/e1aca012-85b8-11e3-96ba-26a915f2fd34.png)

**Comment by ilijalazarevic** [comment] 2014-01-25 14:31
Ok, I have replicated this bug. The problem is with link missing from link field in oc_news_feeds table.

**Comment by ilijalazarevic** [comment] 2014-01-25 17:48
This is hopefully fixed in add662d commit.

**Comment by ilijalazarevic** [comment] 2014-01-25 22:27
cc @Raydiation

**Comment by cosenal** [comment] 2014-01-25 22:48
I wonder if we should allow empty link fields in the db anyway. They might cause other issues.

**Comment by BernhardPosselt** [comment] 2014-01-25 22:50
@icewind1991 just submitted a patch for that some days ago

**Comment by cosenal** [comment] 2014-01-25 23:07
That PR doesnt fix this. Here the issue is about the feed link itself being missing

**Comment by BernhardPosselt** [comment] 2014-01-25 23:11
Ah it was for an item only :)

**Closed as completed** 2014-01-26 18:14 UTC
Labels: bug
